Resources: 
  NodesDynamoDbTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.environment.NODES_TABLE_NAME}
      AttributeDefinitions:
        - AttributeName: uuid
          AttributeType: S
      KeySchema:
        - AttributeName: uuid
          KeyType: HASH
      ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

  MappingsDynamoDbTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.environment.MAPPINGS_TABLE_NAME}
      AttributeDefinitions:
        - AttributeName: uuid
          AttributeType: S
        - AttributeName: name
          AttributeType: S
      KeySchema:
        - AttributeName: uuid
          KeyType: HASH
      ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
      LocalSecondaryIndexes:
        - IndexName: NameIndex
          KeySchema:
            - AttributeName: name
              KeyType: RANGE
          Projection:
            ProjectionType: KEYS_ONLY
              